from flask import request

MAX_USER_NICKNAME_LEN = 35
MIN_USER_NICKNAME_LEN = 4

MAX_USER_FIRSTNAME_LASTNAME_LEN = 20
MIN_USER_FIRSTNAME_LASTNAME_LEN = 4

MAX_USER_EMAIL_LEN = 35
MIN_USER_EMAIL_LEN = 4

MAX_USER_PASSWORD_LEN = 16
MIN_USER_PASSWORD_LEN = 6


MAX_ACTIVITY_TIME_LEFT = 10 * 600  # sec 10 min
MAX_CHECK_PERMISSIONS_TIME_LEFT = 10 * 600  # sec 10 min


def get_inet_ipaddress():
    return request.remote_addr


