"""empty message

Revision ID: f7895d1ea659
Revises: 
Create Date: 2023-10-19 16:07:57.589279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7895d1ea659'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.String(length=300), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('u_index', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('u_last_login_date', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('u_nickname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_realname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('u_index', name='users_pkey'),
    comment='This users admins'
    )
    op.drop_table('articles')
    # ### end Alembic commands ###
